#!/bin/bash

#BSUB -J mjob                        # Job name, for job array "mjob[1-10]"
#BSUB -P aakram                      # Account name (project ID)
#BSUB -G b2_belle2                   # Group for accounting purposes
#BSUB -n 8                           # Number of cores (total across all nodes)
#BSUB -R "span[hosts=1]"             # Request nodes
#BSUB -q s                           # Submit to queue 's' (short jobs < 3h)
#BSUB -W 02:55                       # Runtime (hh:mm)
#BSUB -o logs/%J.out                 # Standard output file (%J is job ID)
#BSUB -e logs/%J.err                 # Standard error file
#BSUB -u adeel.akram@physics.uu.se   # Email address for notifications
#BSUB -B                             # Send email at job start
#BSUB -N                             # Send email at job completion

mkdir -p logs
source /cvmfs/belle.cern.ch/tools/b2setup release-09-00-00

echo "Running job $LSB_JOBID on $(hostname)"
echo "Running job index: $LSB_JOBINDEX"

echo "Job started on $(date)"
basf2 start_sim.py
echo "Job finished on $(date)"
